export const getDataFunction = async url => {
  const getData = async url => {
    const res = await fetch(url)
    const json = await res.json()

    return json
  }

  try {
    const data = await getData(url)
    return data
  } catch (error) {
    console.log(`Произошла ошибка в getData, ${error.message}`)
  }
}

export default getDataFunction